# Generated by Django 5.2 on 2026-02-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policypdf',
            old_name='file',
            new_name='pdf',
        ),
        migrations.RemoveField(
            model_name='policypdf',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='policypdf',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
