# Generated by Django 5.2 on 2026-02-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_rename_file_policypdf_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policypdf',
            name='pdf',
        ),
        migrations.AddField(
            model_name='policypdf',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tax_docs/'),
        ),
    ]
